server:
  port: 8082
spring:
  application:
    name: "webflux-exemplo"
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@webfluxcluster.le9ykia.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=${CLUSTER_NAME}
      auto-index-creation: true

